### ISSUE TITLE
Re: Plotting Data Lab

### ISSUE THREAD

**Issue by RyanPatrickDunn** [learn-co-curriculum/plotting-data-lab#8]
Hi,

For some reason, I'm unable to find a 'Solution' page for this lab. Any idea where I can find the Solutions page for this lab?

Thanks,
Ryan

**Comment by LoreDirick** [comment]
@RyanPatrickDunn the solution is now here, in the [solution branch](https://github.com/learn-co-curriculum/plotting-data-lab/blob/solution/index.ipynb). Thanks for flagging!
